### ISSUE TITLE
Too high initial current draw immediately after plug in of EV

### ISSUE THREAD

**Issue by kletteroli** [SmartEVSE/SmartEVSE-3#19] opened 2022-05-18 11:27 UTC
The SmartEvse with FW. 3.0.1 and in Solar mode with -0A Startup. Mains at 10A and Max at 18A. Single phase.
On plugging in the car I register a current of aprox 18A on my mains which is of short duration (1-3 s). The expected behaviour would be not to surpass the 10 A mains limit. What can be done to avoid this? (I don't want to lower Max)

**Comment by mstegen** [comment] 2022-07-05 17:55
Hi, 
This is caused by the EVSE slowly increasing the charge current, and the EV usually waiting 10-40 seconds before actually drawing current. 
I think the easiest solution would be to add a delay of let's say 60 seconds before increasing the charge current.
This way the EV can start drawing current, at the lowest setting (MIN) and this high initial current draw will not occur.

**Comment by bobosch** [comment] 2022-07-05 21:26
With the git version you could enable automatic StartCurrent detection - this will charge the first  40secs at 6 A

**Comment by elas00** [comment] 2022-08-08 19:05
Where can find firnware with fixed initial current issue?

**Comment by kletteroli** [comment] 2023-02-27 06:31
> Where can find firnware with fixed initial current issue?

The fork "kletteroli" has a fix. It is working for my Leaf/E-NV200.

**Comment by dingo35** [comment] 2024-05-31 11:31
Is this still relevant in v3.6.0?

**Comment by mstegen** [comment] 2024-05-31 13:01
Yes. I think it's good to re-introduce this in our current version.
So that it starts charging at 6A for 40s. And then starts increasing the charge current.

**Comment by mstegen** [comment] 2024-06-06 18:46
Here is a test firmware which will start charging at 6A (or MinCurrent) for 40 seconds, and then starts increasing the charge current. 
[firmware.zip](https://github.com/user-attachments/files/15677972/firmware.zip)

**Comment by mstegen** [comment] 2024-06-19 22:42
This has been implemented in v3.6.2
Closing this now.

**Closed by mstegen** 2024-06-19 22:42 UTC
