### ISSUE TITLE
Multiple SmartEvse controllers in different modes

### ISSUE THREAD

**Issue by badpinguin** [SmartEVSE/SmartEVSE-3#59] opened 2024-08-04 08:11 UTC
**Is your feature request related to a problem? Please describe.**
Currently I have two smartEvse 3s running on the latest firmware v3.6.7. One of them is connected to the sensorbox (P1 connected) with A, B, 12V and ground and the other one with A, B and GND as per the manual. 
If I don't configure the Powershare function on both devices (one to Master and one to Node1) I get a "serial comm error check cfg or wiring". The downside of this Master/Node1 configuration is that it's impossible to use different modes (Smart/Solar) on each device. When I change one of the devices to Smart both of them go to Smart instead of keeping the other one in Solar.
We generally plug in both cars and prioritize charging one car by using Smart and leaving the other one in Solar so that the other one will start to charge if there's solar production and we've left with the other car or when it's full.

**Describe the solution you'd like**
Ability to seperately change the mode on each device.

**Describe alternatives you've considered**
Currently I manually disable one of the chargers or don't plug until we're leaving the one car or it's full. But we have to monitor the progress of the first car in order not to loose any solar production.
We previously used two old SmartEvse (V2) devices and it was working as requested above.

**Additional context**
From what I understand the powershare splits the power equally between the cars. It might be interesting to be able to set a priority so that one car takes the full (solar) power and the other waits until the first is full. It's more interesting to have one car a 80% and one empty instead of both at 40% at the end of the day.

Thanks for considering

**Comment by dingo35** [comment] 2024-08-05 07:31
This is a duplicate of this issue at the dingo35 repo:
https://github.com/dingo35/SmartEVSE-3.5/issues/112

I think the test version posted there does exactly what you are asking for. Please test !!!

**Closed** 2024-09-07 10:41 UTC
